:name: EABlurView
:author: Bushtit Lab
:author_esc: Bushtit%20Lab
:mail: admin@meniny.cn
:desc: Dynamic Blur View
:icon: {name}.png
:version: 1.0.0
:na: N/A
:ios: 8.0
:macos: 10.10
:watchos: {na}
:tvos: {na}
:linux: {na}
:xcode: 9.3
:swift: 5
:license: MIT
:sep: %20%7C%20
:platform: iOS{sep}macOS{sep}watchOS{sep}tvOS{sep}Linux
// :toc: left
:toclevels: 6
:toc-title: TOC
:source-highlighter: highlightjs
// :source-highlighter: pygments
= Meet `{name}`
{author} <{mail}>
v{version}, 2019-04-16

[subs="attributes"]
++++
<p align="center">
  <img src="./Assets/{icon}" alt="{name}" height="200px">
  <br/><br/>
  <img alt="Author" src="https://img.shields.io/badge/author-{author_esc}-blue.svg">
  <img alt="EMail" src="https://img.shields.io/badge/mail-{mail}-orange.svg">
  <img alt="MIT" src="https://img.shields.io/badge/license-{license}-blue.svg">
  <br/>
  <img alt="Version" src="https://img.shields.io/badge/version-{version}-brightgreen.svg">
  <img alt="Platforms" src="https://img.shields.io/badge/platform-{platform}-lightgrey.svg">
  <img alt="Swift" src="https://img.shields.io/badge/swift-{swift}%2B-orange.svg">
  <br/>
  <img alt="Build Passing" src="https://img.shields.io/badge/build-passing-brightgreen.svg">
  <img alt="Cocoapods" src="https://img.shields.io/badge/cocoapods-compatible-brightgreen.svg">
  <img alt="Carthage" src="https://img.shields.io/badge/carthage-compatible-brightgreen.svg">
  <img alt="SPM" src="https://img.shields.io/badge/spm-compatible-brightgreen.svg">
</p>
++++

:toc:

== 🏵 Introduction

**{name}** is {desc}.

== 📋 Requirements

[%header]
|===
2+^m|Type 1+^m|Requirement

1.5+^.^|Platform ^|iOS ^|{ios}
^|macOS ^|{macos}
^|tvOS ^|{tvos}
^|watchOS ^|{watchos}
^|Linux ^|{linux}

^|IDE ^|Xcode ^| {xcode}
^|Language ^|Swift ^| {swift}
|===

== 📲 Installation

=== CocoaPods

`{name}` is available on link:https://cocoapods.org[CocoaPods].

[source, ruby, subs="verbatim,attributes"]
----
use_frameworks!
pod '{name}'
----

=== Manually

Copy all files in the `{name}` directory into your project.

== 🛌 Dependency

* link:https://github.com/Meniny/DependencyName[DependencyName]

== 📱 Sample Project

Run `pod install` at `Sample/` first.

== ❤️ Contribution

You are welcome to fork and submit pull requests.

== 🔖 License

`{name}` is open-sourced software, licensed under the link:./LICENSE.md[`{license}`] license.

== 🔫 Usage

[source, swift, subs="verbatim,attributes"]
----
import {name}
----

=== Example

Blur the whole

[source, swift, subs="verbatim,attributes"]
----
let blurView = DynamicBlurView(frame: view.bounds)
blurView.blurRadius = 10
view.addSubview(blurView)
----

Animation

[source, swift, subs="verbatim,attributes"]
----
UIView.animateWithDuration(0.5) {
    blurView.blurRadius = 30
}
----

Ratio

[source, swift, subs="verbatim,attributes"]
----
blurView.blurRatio = 0.5
----

### Variable

[source, swift, subs="verbatim,attributes"]
----
var drawsAsynchronously: Bool
----

- When true, it captures displays image and blur it asynchronously. Try to set true if needs more performance.
- Asynchronous drawing is possibly crash when needs to process on main thread that drawing with animation for example.
- Default is false.

[source, swift, subs="verbatim,attributes"]
----
var blurRadius: CGFloat
----

- Strength of the blur.

[source, swift, subs="verbatim,attributes"]
----
var trackingMode: TrackingMode
----

- Mode for update frequency.
- `Common` is constantly updated.
- `Tracking` is only during scrolling update.
- `None` is not update.

[source, swift, subs="verbatim,attributes"]
----
var blendColor: UIColor?
----

- Blend in the blurred image.

[source, swift, subs="verbatim,attributes"]
----
var iterations: Int
----

- Number of times for blur.
- Default is 3.

[source, swift, subs="verbatim,attributes"]
----
var isDeepRendering: Bool
----

- If the view want to render beyond the layer, should be true.
- Default is false.

[source, swift, subs="verbatim,attributes"]
----
var blurRatio: CGFloat
----

- When none of tracking mode, it can change the radius of blur with the ratio. Should set from 0 to 1.
- Default is 1.

[source, swift, subs="verbatim,attributes"]
----
var quality: CaptureQuality
----

- Quality of captured image.
- Default is medium.

### Function

[source, swift, subs="verbatim,attributes"]
----
func refresh()
----

- Remove cache of blur image then get it again.

[source, swift, subs="verbatim,attributes"]
----
func remove()
----

- Remove cache of blur image.

[source, swift, subs="verbatim,attributes"]
----
func animate()
----

- Should use when needs to change layout with animation when is set none of tracking mode.
